name: duchow_orm
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: #^2.16.0
  sqlite3_flutter_libs: #^0.5.17
  path_provider: #^2.1.1
  path: #^1.8.3
  analyzer: #^3.3.1
  build: #^2.4.1
  source_gen: #^1.4.0
