name: duchow_orm
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

  analyzer: '>=5.2.0 <7.0.0'
  build: ^2.0.0
  source_gen: any

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0

#dependency_overrides:
#  source_gen:
#    path: ../source_gen
