name: duchow_orm
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  sqlite3: ^2.4.0