name: duchow_orm
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.1.1
  path: ^1.8.3
  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.4.0
